backend:
  name: github
  repo: MarianaVilasBoas/sveltia
  branch: main

media_folder: assets/images

collections:
  - name: docs
    label: Manuais
    folder: docs
    create: true
    fields:
      - { label: Titulo, name: title, widget: string }
      - { label: Conteudo, name: body, widget: markdown }
