backend:
  name: github
  repo: MarianaVilasBoas/sveltia
  branch: main
  client_id: Ov23livKtkdid9D5minB
  base_url: https://sveltia-cms-auth.pages.dev

media_folder: assets/images

collections:
  - name: docs
    label: Manuais
    folder: docs
    create: true
    fields:
      - { label: Titulo, name: title, widget: string }
      - { label: Conteudo, name: body, widget: markdown }
